config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :users, only: [:new, :create, :show] do
    resources :favorites, only: [:create]
  end

  resources :categories, only: [:show, :new, :create] do
    resources :jifs, only: [:show]
  end

  namespace :admin do
    resources :users, only: [:show, :index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :jifs, dependent: :delete_all
  validates :name, presence: true, uniqueness: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates :user, presence: true
  validates :jif, presence: true
  belongs_to :user
  belongs_to :jif
end

app/models/jif.rb
class Jif < ActiveRecord::Base
  belongs_to :category
  has_many :favorites
  has_many :users, through: :favorites

  validates :jif_path,    presence:   true,
                          uniqueness: true
  validates :static_path, presence:   true,
                          uniqueness: true
  validates :category, presence:   true
  validates :width, presence:   true
  validates :height, presence:   true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :role,     presence:   true

  has_many :favorites
  has_many :jifs, through: :favorites

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_categories
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def find_categories
    @categories = Category.all
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def search_jifs(category)
    Giphy.search(category, {limit: 500})
  end

  def generate_jifs(category, jifs)
    random_count = (jifs.count * 2)
    random_count.times do
      jif = Giphy.random(@category.name)
      @category.jifs.create(jif_path: jif.image_url.to_s, static_path: JSON.parse(jif.to_json)["hash"]["fixed_height_small_still_url"], width: jif.image_width, height: jif.image_height)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_categories
  def show
    find_category
  end

  def new
  end

  def create
    @category = Category.new(category_params)
    jifs = search_jifs(@category.name)
    if jifs.empty?
      flash[:notice] = "Hey, there's no jifs for this category name.  ABORT. ABORT. ABORT."
      redirect_to admin_user_path(current_user)
    elsif @category.save
      generate_jifs(@category, jifs)
      flash[:notice] = "Jifs have been created."
      redirect_to admin_user_path(current_user)
    else
      flash[:notice] = "Hey, this categroy already exists."
      redirect_to admin_user_path(current_user)
    end
  end

private
  def find_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @jif = Jif.find(params[:jif_id])
    @favorite = @user.favorites.find_or_initialize_by(jif_id: params[:jif_id])
    if @favorite.save
      redirect_to user_path(@user)
    else
      flash[:notice] = "You've already favorited!"
      redirect_to category_jif_path(@jif.category_id, @jif)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jifs_controller.rb
class JifsController < ApplicationController
  before_action :find_categories
  before_action :find_category
  before_action :find_jif
  def show
  end

private
  def find_category
    @category = Category.find(params[:category_id])
  end

  def find_jif
    @jif = Jif.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to check_status
    else
      flash.now[:error] = "Hey, it looks you may have made a typo... Try again."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

private
  def check_status
    if @user.admin?
      return admin_user_path(@user)
    else
      return @user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user
  before_action :find_categories

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:notice] = "Sorry Jifster, something went wrong :(... Please try again."
      render :new
    end
  end

  def show
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jifs_helper.rb
module JifsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1>ADMIN!</h1>

app/views/admin/users/show.html.erb
<%= render partial: "shared/nav" %>
<div class="container">
  <div class="row">
    <%= render partial: "shared/categories" %>
    <div id="" class="col-xs-9 form-group text-center form-div">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "container flash_#{type}" %>
      <% end %><br>
      <%= form_for(:category, url: categories_path(@category)) do |f| %>
        <%= f.label :name, class:"sr-only"  %>
        <%= f.text_field :name, placeholder: "category", class:"form-control text-input" %><br>
        <%= f.submit "CREATE", class:"btn btn-login" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= render partial: "shared/nav" %>
<div class="container">
  <div class="row">
    <%= render partial: "shared/categories" %>
    <div id="category" class="col-xs-9 show-header">
      <div id="jifs" class="row text-center jifs">
        <% if @category.jifs.empty? %>
          No jifs yet!
        <% else %>
          <% @category.jifs.each do |jif| %>
          <div class="col-xs-6 col-sm-4 col-md-3 jif" >
            <%= link_to image_tag(jif.jif_path, class: "jifs_images", width: "150", height: "150"), category_jif_path(@category, jif), id: "#{jif.id}-jif" %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: "shared/nav" %>
  <div class="row">
    <div id="category" class="col-xs-12">
      <div id="jifs" class="row jifs">
          <% Jif.all.order('random()').each do |jif| %>
            <div class="col-xs-6 col-sm-2 jif", >
              <%= link_to image_tag(jif.jif_path, class: "jifs_images", width: "150", height: "150"), category_jif_path(jif.category_id, jif), id: "#{jif.id}-jif" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/jifs/show.html.erb
<%= render partial: "shared/nav" %>
<div class="container-fluid jif-container">
  <div id="show_jif">
    <%= link_to image_tag(@jif.jif_path, class: "jifs-images", height: @jif.height, width: @jif.width), category_jif_path(@category, @jif), {class: 'jif_path', id: "#{@jif.id}-jif" } %>
  </div>
</div>
<div id="jif-info" class="container-fluid jif-info-container">
  <div class="form-group text-center">
    <% if current_user %>
      <%= form_for(:favorite, url: user_favorites_path(current_user)) do |f| %>
        <%= hidden_field_tag(:user_id, current_user.id) %>
        <%= hidden_field_tag(:jif_id, @jif.id) %><br>
        <%= f.submit "Favorite this jif!", class:"btn btn-login" %>
        <%= link_to "Category: #{@category.name}", category_path(@category), class: "btn btn-signup" %>
      <% end %>
    <% end %>
    <div class="source">
      source: <%= @jif.jif_path %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jiffy</title>
    <%= stylesheet_link_tag    'normalize', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'bootstrap-social', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_categories.html.erb
<div id="categories" class="col-xs-3 show-header">
  Categories
  <div class="row">
    <% if @category %>
      <div class="col-xs-12 cat-link-active">
        <%= link_to @category.name, category_path(@category) %>
      </div>
    <% end %>
    <% @categories.order(:name).each do |cat| %>
      <% if @category == cat %>
      <% else %>
        <div class="col-xs-12 cat-link">
          <%= link_to cat.name, category_path(cat) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="container-fluid">
    <div class="logo">
      <%= link_to image_tag("logo.png"), root_path, id:"logo-img" %>
    </div>
    <ul class="main-nav">
      <% if current_user %>
        <li><%= link_to "HOME", user_path(current_user) %></li>
        <li><%= link_to "LOGOUT", logout_path, method: :delete %></li>
      <% elsif %>
        <li><%= link_to "LOGIN", login_path %></li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/users/_signup_form.html.erb
<div class="container">
  <div class="form-group text-center form-div">
    <%= link_to image_tag("logo.png"), root_path, class:"logo-img-form-page" %>
    <%= form_for(@user) do |f| %>
      <%= f.label :username, class:"sr-only"  %>
      <%= f.text_field :username, placeholder: "username", class:"form-control text-input" %><br>
      <%= f.label :email, class:"sr-only"  %>
      <%= f.text_field :email, placeholder: "email", class:"form-control text-input" %><br>
      <%= f.label :password, class:"sr-only"  %>
      <%= f.password_field :password, placeholder: "password", class:"form-control text-input" %><br>
      <%= f.submit "JOIN", class:"btn btn-signup" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render partial: "signup_form" %>

app/views/users/show.html.erb
<%= render partial: "shared/nav" %>
<div class="container">
  <div class="username">
    <%= @user.username.upcase %>
  </div>
  <div class="row">
    <%= render partial: "shared/categories" %>
    <div id="favorite_jifs" class="col-xs-9 show-header">
      <div id="jifs" class="row text-center jifs">
        <% if @user.jifs.empty? %>
          No jifs yet!
        <% else %>
          <% @user.jifs.each do |jif| %>
          <div class="col-xs-6 col-sm-4 col-md-3 jif">
            <%= link_to image_tag(jif.jif_path, class: "jifs_images", width: "150", height: "150"), category_jif_path(jif.category_id, jif), {class: 'jif_path', id: "#{jif.id}-jif" } %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>